# Generated by Django 5.2.5 on 2025-09-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        help_text="Nom et prénom de l'élève",
                        max_length=200,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage obtenu",
                        max_digits=5,
                        verbose_name="Pourcentage",
                    ),
                ),
                (
                    "classe",
                    models.CharField(
                        help_text="Classe de l'élève",
                        max_length=50,
                        verbose_name="Classe",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Section de l'élève",
                        max_length=50,
                        verbose_name="Section",
                    ),
                ),
                (
                    "annee_scolaire",
                    models.CharField(
                        help_text="Année scolaire (ex: 2023-2024)",
                        max_length=20,
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "date_import",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'import"
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat élève",
                "verbose_name_plural": "Résultats élèves",
                "ordering": ["-pourcentage", "nom_complet"],
            },
        ),
    ]
