# Generated by Django 5.2.5 on 2025-09-02 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palmares_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnneeScolaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.CharField(
                        help_text="Format: 2023-2024",
                        max_length=9,
                        unique=True,
                        verbose_name="Année scolaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-annee"],
            },
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la classe (ex: 6ème A, Terminale S)",
                        max_length=100,
                        unique=True,
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        db_index=True,
                        help_text="Nom et prénom complet de l'élève",
                        max_length=255,
                        unique=True,
                        verbose_name="Nom complet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élève",
                "verbose_name_plural": "Élèves",
                "ordering": ["nom_complet"],
            },
        ),
        migrations.CreateModel(
            name="Resultat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage obtenu",
                        max_digits=5,
                        verbose_name="Pourcentage",
                    ),
                ),
                (
                    "date_import",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'import"
                    ),
                ),
                (
                    "annee_scolaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats",
                        to="palmares_app.anneescolaire",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultats",
                        to="palmares_app.classe",
                        verbose_name="Classe",
                    ),
                ),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultats",
                        to="palmares_app.eleve",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat",
                "verbose_name_plural": "Résultats",
                "ordering": ["-pourcentage", "eleve__nom_complet"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom de la section (ex: Scientifique, Littéraire, Economique)",
                        max_length=100,
                        unique=True,
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
                "ordering": ["nom"],
            },
        ),
        migrations.DeleteModel(
            name="StudentRecord",
        ),
        migrations.AddField(
            model_name="resultat",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resultats",
                to="palmares_app.section",
                verbose_name="Section",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resultat",
            unique_together={("eleve", "annee_scolaire")},
        ),
    ]
