# Generated by Django 5.2.5 on 2025-09-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("palmares_app", "0002_anneescolaire_classe_eleve_resultat_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultat",
            name="pourcentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pourcentage obtenu",
                max_digits=5,
                null=True,
                verbose_name="Pourcentage",
            ),
        ),
    ]
